{ lib }:

{
  compatibility,
  version,
}:

let
  versionMajor = builtins.head (lib.splitString "." version);
in
assert lib.assertMsg (
  compatibility == "SameMajorVersion"
) "unsupported CMake package version compatibility: ${compatibility}";
''
  set(PACKAGE_VERSION "${version}")

  if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
    set(PACKAGE_VERSION_COMPATIBLE FALSE)
  else()
    set(_KRITA_CVF_VERSION_MAJOR "${versionMajor}")

    if(PACKAGE_FIND_VERSION_RANGE)
      math(EXPR _KRITA_CVF_VERSION_MAJOR_NEXT "''${_KRITA_CVF_VERSION_MAJOR} + 1")
      if(NOT PACKAGE_FIND_VERSION_MIN_MAJOR STREQUAL _KRITA_CVF_VERSION_MAJOR
          OR ((PACKAGE_FIND_VERSION_RANGE_MAX STREQUAL "INCLUDE"
              AND NOT PACKAGE_FIND_VERSION_MAX_MAJOR STREQUAL _KRITA_CVF_VERSION_MAJOR)
            OR (PACKAGE_FIND_VERSION_RANGE_MAX STREQUAL "EXCLUDE"
              AND NOT PACKAGE_FIND_VERSION_MAX VERSION_LESS_EQUAL _KRITA_CVF_VERSION_MAJOR_NEXT)))
        set(PACKAGE_VERSION_COMPATIBLE FALSE)
      elseif(PACKAGE_FIND_VERSION_MIN_MAJOR STREQUAL _KRITA_CVF_VERSION_MAJOR
          AND ((PACKAGE_FIND_VERSION_RANGE_MAX STREQUAL "INCLUDE"
              AND PACKAGE_VERSION VERSION_LESS_EQUAL PACKAGE_FIND_VERSION_MAX)
            OR (PACKAGE_FIND_VERSION_RANGE_MAX STREQUAL "EXCLUDE"
              AND PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION_MAX)))
        set(PACKAGE_VERSION_COMPATIBLE TRUE)
      else()
        set(PACKAGE_VERSION_COMPATIBLE FALSE)
      endif()
      unset(_KRITA_CVF_VERSION_MAJOR_NEXT)
    else()
      if(PACKAGE_FIND_VERSION_MAJOR STREQUAL _KRITA_CVF_VERSION_MAJOR)
        set(PACKAGE_VERSION_COMPATIBLE TRUE)
      else()
        set(PACKAGE_VERSION_COMPATIBLE FALSE)
      endif()

      if(PACKAGE_FIND_VERSION STREQUAL PACKAGE_VERSION)
        set(PACKAGE_VERSION_EXACT TRUE)
      endif()
    endif()

    unset(_KRITA_CVF_VERSION_MAJOR)
  endif()
''
